# Admin controllers live behind /admin and forumify expects their route names to start
# with forumify_admin_.
command_net_s3_admin:
    resource: ../src/Admin/Controller
    type: attribute
    name_prefix: forumify_admin_
    prefix: admin/

# Frontend controllers.
command_net_s3:
    resource: ../src/Controller
    type: attribute
    name_prefix: command_net_s3_
